### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by DavidePastore** [Greg0/Lazer-Database#10]
Hi Greg,
we need a lot of unit tests for a library like this, to be sure that things work after changes and to rapidly test new features.

Thanks

**Comment by Greg0** [comment]
Hi, yes i was thinking about that but at this moment i don't have so much time to do this.

**Comment by Greg0** [comment]
Checkout new branch, tests in progress

**Comment by DavidePastore** [comment]
@Greg0 Good job!

**Comment by Greg0** [comment]
I have mergesd tests from parallel branch. 
Relations are not tested at all
df82c8bc7ed4d72f5eb8579ae4ed3227ba7aaf32
