### ISSUE TITLE
Unique fileds

### ISSUE THREAD

**Issue by Tantacula** [Greg0/Lazer-Database#13]
Is it possible to add unique key functionality for some fileds, when creating new table?

**Comment by Greg0** [comment]
Yes it is possible but I must analyze that problem deeper,  think how to do this and do not mess speed

**Comment by Tantacula** [comment]
What you think about next algoritm: first calling of "save" function creates an array with all values in unique column (for each columns) and after that every "save()" compares value with this array. Its just tip of the iceberg, but if table has not unique keys, speed will not changed. Sorry for my english and for my laziness :)
