### ISSUE TITLE
db structure

### ISSUE THREAD

**Issue by AchrafSoltani** [Greg0/Lazer-Database#17]
Hi, I have checked the library and it's seems to be a complete solution, but I have a couple of questions : 
- Is database structure created only by code ? if so, is there an automatic check for an existing table or does it just throw an error.
- Are we supposed to call the init scripts (database creation) and relation definition before executing queries ? I mean, are the relations defined inside the factory (code) or persisted somewhere else ?

**Comment by FalkoJoseph** [comment]
I don't think it checks for existing tables. Ran into a couple of errors there as well. I might be wrong though.

**Comment by Greg0** [comment]
1. Yes, structure is created only by the code (you can do it by yourself if you know how), there is no automatic checker for existing tables BUT if you'll export to JSON your table from MySQL by PHPmyAdmin you will be able to use it in Lazer, only restriction is to create config file for that exported table.

2. You should call database creation if you want to execute query on it. Relations are optional, only if you need them.
