### ISSUE TITLE
Lazer cannot load up with FlightPHP

### ISSUE THREAD

**Issue by OfficialJoe** [Greg0/Lazer-Database#18]
Hey There,

I use flight PHP due his easy usage and features that it brings but I want to 
also use Lazer DB because it is the only good json DB that is out there only 
when I try to load it up it bings up some error..

Error: http://pastebin.com/TuVx65UL
Loader(autoload.php): http://pastebin.com/GuTFucyP

When I do remove Flight lazer stops giving errors etc so I think I do something wrong or it wont work together.

*Autoload is not from any framework etc this is the file where I load all the stuff that is needed to keep it orginized.

**Comment by Greg0** [comment]
I didn't look closely to your code but It is in 90% problem with your autoloader. 
I have question why you not using composer?

**Comment by OfficialJoe** [comment]
Cause I cannot get it working on my windows PC and I do not know if my Web hoster supports that if Im gonna put it up to my Web Server ( if it needs support )

**Comment by Greg0** [comment]
I will help you, to use on hosting only composer autoloader you do not need any support on it. You can add dependecy (download) what you need via composer locally then upload ready to run environment.
What problems you have on your Win PC with composer? It has exe installer.

**Comment by OfficialJoe** [comment]
Oke thanks I will try to install it again and if I have issues I post it here, if that is fine?

**Comment by Greg0** [comment]
yep, you shoudl enable openssl in your server. I guess you are using easyPHP so I found solution http://stackoverflow.com/a/18117887

**Comment by OfficialJoe** [comment]
Oke thanks I got it installed I will now need to find out via there get started or something how to use it and after that how to update my project

**Comment by OfficialJoe** [comment]
Oke thanks I got it working now! Everything works fine together!

**Comment by Greg0** [comment]
I'm glad. Hope you'll enjoy it
