### ISSUE TITLE
Mixed character encodings break the JSON table data files

### ISSUE THREAD

**Issue by IkarosKappler** [Greg0/Lazer-Database#24]
I created a database and inserted ISO-8859-1 encoded string data.
Later on I tried to insert more data with UTF-8 encoding and received this error:

`Warning: array_push() expects parameter 1 to be array, null given in /Lazer/Classes/Core/Database.php on line 795`

This did not just fail but destroyed the whole data in the JSON table document (the document had only 4 bytes after this, containing 'null').

No more database operations were possible after this. I fixed it by converting all incoming string data to UTF-8 always, but maybe you want to be aware of this issue.

**Comment by Greg0** [comment]
Fixed in f24f46f8f7486a58d7cf4ce5638a51a418e76dda
