### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by gorlovka** [Greg0/Lazer-Database#25]
Composer require  reaps:

Using version ^1.1 for greg0/lazer-database
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phpunit/phpunit[4.5.1, 5.4.6].
    - Can only install one of: phpunit/phpunit[5.4.6, 4.5.1].
    - Can only install one of: phpunit/phpunit[4.5.1, 5.4.6].
    - greg0/lazer-database 1.1 requires phpunit/phpunit 4.5.1 -> satisfiable by phpunit/phpunit[4.5.1].
    - Installation request for greg0/lazer-database ^1.1 -> satisfiable by greg0/lazer-database[1.1].
    - Installation request for phpunit/phpunit (locked at 5.4.6) -> satisfiable by phpunit/phpunit[5.4.6].

I  see you pointed dependency on "phpunit/phpunit: 4.5.1"  thought  phpunit 5.4 is available. Any reasons why?

**Comment by Greg0** [comment]
Resolved
