### ISSUE TITLE
Custom model 

### ISSUE THREAD

**Issue by emildd** [Greg0/Lazer-Database#28]
Hi, I have a problem at my cutom model.
my class 
`use Lazer\Classes\Database;
class Test extends Database
{
    protected $name = "test";
}`

result:
`<b>Warning</b>:  Creating default object from empty value in <b>`
`/vendor/greg0/lazer-database/src/Lazer/Classes/Core/Database.php on line 794`

var_dump result: 
`object(Test)#28 (7) {
  ["name":protected]=>
  string(4) "test"
  ["data":protected]=>
  NULL
  ["set":protected]=>
  object(stdClass)#29 (2) {
    ["id"]=>
    int(1)
    ["names"]=>
    string(4) "test"
  }
  ["currentId":protected]=>
  int(1)
  ["currentKey":protected]=>
  int(0)
  ["pending":protected]=>
  NULL
  ["resetKeys":protected]=>
  int(1)
}`

can you help this? 

Thank you

**Comment by Greg0** [comment]
It is all code?
I think it is not necessary to create class like `Test` here. However code is old, not elegant, buggy and project is dead.
