### ISSUE TITLE
using again use Lazer\Classes\Database as Lazer

### ISSUE THREAD

**Issue by hoangnamitc** [Greg0/Lazer-Database#29]
hi adm,

I have file a.php and file b.php

File A:
use Lazer\Classes\Database as Lazer;
Lazer:table('table')->findAll()  (oke working)
include b.php

File B:
Lazer:table('table')->findAll()  (not working)

so how to extend Lazer from file A but setting namespace again in file B included in file A

tks

**Comment by Greg0** [comment]
Use statement should be defined in every file. This project is old and not maintained. It can be little buggy. SQLite should be well alternative.

**Comment by hoangnamitc** [comment]
Can you recommend me a class to save data in json format?
To replace this too old project. Or did you not upgrade this project?

**Comment by Greg0** [comment]
It depends on your requirement. Can you tell something more about way you want use it?

**Comment by hoangnamitc** [comment]
I need one class can use select,insert,update,delete like database mysql but is json 💃

**Comment by Greg0** [comment]
I know only my library and flywheel. You can search it on github

**Comment by hoangnamitc** [comment]
Thanks you !
