### ISSUE TITLE
If dead, mark as dead

### ISSUE THREAD

**Issue by jacmoe** [Greg0/Lazer-Database#30]
I think there's an option to mark a project as not maintained.

I am not happy that the project is dead, but I have been in open source long enough to know that real life can get in the way, interests can change, and that we can't always have or give what we want all the time.

I have been a happy user of this library for some time now, but it's probably time to move on.
Unfortunately, I am not in a position to contribute/maintain this project, but I hope that someone else will.

Thanks for Lazer-Database - it has been great! :)

It would be a good idea if the project was set to not maintained (it can be reversed), so that people are made aware of the state of affairs.
Thanks :)

**Comment by anant-svc** [comment]
@jacmoe I've have removed **UNMAINTAINED** text and package is maintained by me also.

**Comment by anant-svc** [comment]
@jacmoe I've have removed UNMAINTAINED text and package is maintained by me also. You can use the package and report issues now.

**Comment by parkerj** [comment]
Awesome! I also use this in several projects, so glad to here it is still alive.

**Comment by anant-svc** [comment]
Good to hear that you are using it. If any issues report it & will try to fix it asap.

**Comment by jacmoe** [comment]
I was hoping that this would happen, and I am glad that it did! 😄 
This project works so well, and now I can continue to use it - that is great!
I will try and help as much as I can, if I stumble over rough edges.
Thank you 👍

**Comment by simon511000** [comment]
It's awesome ! I use it too

**Comment by anant-svc** [comment]
I want some benchmark reports from you all. This will help in improve the performance of Lazer. Benchmark Reports format is not fixed. Also suggestions are welcomed.

**Comment by Greg0** [comment]
I've applied some improvements to library. Updated phpunit and readme, reorganized classes. Fixed some bugs in closed issues like char encoding.

**Comment by Greg0** [comment]
All this thing available in version 1.1.3

**Comment by SaphiLC** [comment]
yay so its still alive? :D i found this project today and cant wait to play with it :]
