### ISSUE TITLE
How can I choose the subdirectory?

### ISSUE THREAD

**Issue by Jtreix** [Greg0/Lazer-Database#32]
Hi,
How can i choose subdirectory,
`define('LAZER_DATA_PATH', '../db/') `**or** `define('LAZER_DATA_PATH', realpath(__DIR__).'/../db/')`
not working.
Thanks.

**Comment by Jtreix** [comment]
here is the solution
define('LAZER_DATA_PATH', $_SERVER['DOCUMENT_ROOT'].'/kernel/db/');

**Comment by anant-svc** [comment]
There 1% mistake in your code: corrected below:
`define('LAZER_DATA_PATH', realpath(__DIR__ . '/../db/'));`

**Comment by anant-svc** [comment]
You can also define ROOT constant on index.php and supply it in realpath function.

**Comment by Jtreix** [comment]
Thanks so much.
