### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by Jtreix** [Greg0/Lazer-Database#33]
How can i eliminate case sensitivity?
Thanks.

**Comment by anant-svc** [comment]
Please describe the test cases?

**Comment by Jtreix** [comment]
"Jtreix" the query I apply to this nick;
`
$row = DB::table('users')->where('username', '=', strip_tags($_GET['par']))->find();
`

**Comment by anant-svc** [comment]
I just now checked version `1.1.4` and found the case sensitivity is eliminated already.

**Comment by anant-svc** [comment]
I just now checked version 1.1.4 and found the case sensitivity is eliminated in `findAll` function.

**Comment by Greg0** [comment]
Yep, that was done in 2015 
rev: 735f0e7adceceef269dec4cb7351c3397d557e9c
