### ISSUE TITLE
Insert & Update Methods

### ISSUE THREAD

**Issue by parkerj** [Greg0/Lazer-Database#37]
Is it possible to add `insert` and `update` methods, so that it works like below?
```
$row = Lazer::table('table_name');
$row->insert([
    'nickname' => 'new_user'
])->save();

$row = Lazer::table('table_name')->find(1);
$row->update([
    'nickname' => 'updated_user'
])->save();
```

**Comment by Greg0** [comment]
Do it. Magic properties always was bad idea :)

**Comment by anant-svc** [comment]
@parkerj @Greg0 Hi, working on new feature request will add `set` method for `insert` & `update`.

**Comment by parkerj** [comment]
Awesome! Thank you.

**Comment by Greg0** [comment]
Solved
