### ISSUE TITLE
type double is Wrong data type

### ISSUE THREAD

**Issue by hoangnamitc** [Greg0/Lazer-Database#47]
![image](https://user-images.githubusercontent.com/7042462/47897758-8d83df00-dea5-11e8-86f9-9b878329d5e6.png)

![image](https://user-images.githubusercontent.com/7042462/47897882-1ef35100-dea6-11e8-926e-746bd72e5a71.png)

but i change to interger or string is working

**Comment by hoangnamitc** [comment]
both cases

**Comment by paperduck** [comment]
I'm still getting this error when I try to insert into a table that has a field of type "double".

**Comment by Greg0** [comment]
Are you using newest package version `v1.1.6` ?

**Comment by Greg0** [comment]
I see now. @anant-svc made PR but not merged it.

**Comment by anant-svc** [comment]
@Greg0 @paperduck I have merged the PR, check it now

**Comment by Greg0** [comment]
@anant-svc release new version of package then, please.

**Comment by anant-svc** [comment]
Okay

**Comment by anant-svc** [comment]
Created new release: 1.1.7, check here: https://github.com/Greg0/Lazer-Database/releases
