### ISSUE TITLE
How to accept null data

### ISSUE THREAD

**Issue by hoangnamitc** [Greg0/Lazer-Database#48]
My field data is null.
'Lazer\Classes\LazerException' with message 'There is no data'

How to ignore warning if null.

**Comment by anant-svc** [comment]
@hoangnamitc I have tested via PHPUnit and found it an issue in core. Will fix it asap.

**Comment by hoangnamitc** [comment]
@anant-svc  Thanks bro, I'm still waiting

**Comment by anant-svc** [comment]
I have commit the fix here  [93fed68]([url](https://github.com/Greg0/Lazer-Database/commit/93fed68ff0cb1b7430e20e204892db48f1fa36d2))
Please test at your end if it fix the error

**Comment by Greg0** [comment]
Fixed. Available in version 1.1.6
