### ISSUE TITLE
Make Tables in Some Directory

### ISSUE THREAD

**Issue by Pedroxam** [Greg0/Lazer-Database#51]
Hi.
i want to add uniq table for each user in new directory.

look this eg:

```
define('LAZER_DATA_PATH','./storage/'); // I want this to be dynamic.  For example, I want to store json's file in a folder with the user's id name.
```

tnx.

**Comment by ananth-iyer** [comment]
@Pedroxam That couldn't be possible because of current implementation is already used by other PHP libraries. And changing CURD operations is time consuming for me. I can bugfix issues reported or improve code quality.

Although you can clone the repository and implement your logic there.

**Comment by anant-svc** [comment]
@Pedroxam That couldn't be possible because of current implementation is already used by other PHP libraries. And changing CURD operations is time consuming for me. I can bugfix issues reported or improve code quality.

Although you can clone the repository and implement your logic there.

**Comment by Greg0** [comment]
There is no possibility to store same entities in separate files. This is designed to store many entities of the same type in one file like rows in table

**Comment by Pedroxam** [comment]
Ok and Thanks, I found another way.

**Comment by bahramzade** [comment]
Can I make different folders for the data storage logic in one file?

**Comment by Greg0** [comment]
> Can I make different folders for the data storage logic in one file?

It also can't store specific files in different locations. Lazer store files like tables in one place without grouping them.

**Comment by anant-svc** [comment]
@Greg0 I think many are asking for this feature from long time. Please give your valuable feedback to implement it.
