### ISSUE TITLE
Array Type Check?

### ISSUE THREAD

**Issue by parkerj** [Greg0/Lazer-Database#52]
Feature request: want to know if it is possible for you to add `array` to the type check when creating a table: `array( 'boolean', 'integer', 'string', 'double', 'array' )`.

Reason is that since you now have the set method, I would love to be able to do something like this:

```php
$row = Lazer::table('user');

$row->set(array(
    'nickname' => 'user',
    'email' => 'user@example.com',
    'attributes' => [
        'job' => 'Developer',
        'hobbies' => 'basketball, traveling, hiking',
        'favorite_food' => 'pizza'
    ]
));
$row->save();
```

**Comment by anant-svc** [comment]
@parkerj Yes, it is possible to add `array` type. I will let you know once done.

**Comment by parkerj** [comment]
@anant-svc Awesome, thanks!!!

**Comment by anant-svc** [comment]
@parkerj I am working on out of box filter for array type

**Comment by parkerj** [comment]
@anant-svc Ok, thanks for working on this.

**Comment by Greg0** [comment]
@parkerj You can use relations here and store attributes in separate table.

**Comment by Greg0** [comment]
For example:

```php
$users = Lazer::table('user')->with('attributes')->findAll();

foreach ($users as $user) {
   echo 'Name: ' . $user->nickname . PHP_EOL;
   foreach ($user->Attributes as $attribute) {
      echo sprintf('%s: %s', $attribute->name, $attribute->value) . PHP_EOL;
   }
}
```
