### ISSUE TITLE
How to use limit with asArray

### ISSUE THREAD

**Issue by hoangnamitc** [Greg0/Lazer-Database#54]
Hi Guys,

My problem is I'm want use limit() and asArray()?

Lazer::table('tbl')->findAll()->asArray()->limit(2); (error)

method asArray() and limit() are required after find() or findAll()

So how do I do it?

tks

**Comment by Greg0** [comment]
Try findAll()->limit(5)->asArray()

**Comment by Greg0** [comment]
https://github.com/Greg0/Lazer-Database/blob/master/docs/examples.md

**Comment by hoangnamitc** [comment]
Thanks @Greg0  support me,

My code working!
