### ISSUE TITLE
Join condition in Lazer

### ISSUE THREAD

**Issue by hoangnamitc** [Greg0/Lazer-Database#55]
hi guy,

Lazer can join condition multiple line?

Example:
```
$row = Lazer::table('table')->where('public', '=', 1);

if (condition) {
    $row->where('permission', '=', 1);
}

$data = $row->findAll();
```

Thanks!

**Comment by anant-svc** [comment]
Hi, "where" returns the _Lazer\Classes\Database_ class so join condition later will work & to get data you have called _findAll_ method

**Comment by hoangnamitc** [comment]
Yes, Thanks Bro!
