### ISSUE TITLE
Packagist issues after last package update 

### ISSUE THREAD

**Issue by Greg0** [Greg0/Lazer-Database#59]
@anant-svc I received email from packagist

## greg0/lazer-database failed to update, invalid composer.json data

The greg0/lazer-database package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

**Comment by anant-svc** [comment]
@Greg0 I have executed the `composer validate` and it is showing below errors:

Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.

Let me know your suggestions for above issue.

**Comment by anant-svc** [comment]
@Greg0 Composer 2.0 will roll out in coming days and before that packagist wants the project must us clean without any future issues.

I have fixed the issue because "composer.json" was using require-dev.mikey179/vfs**S**tream that is replaced with the stable version of the same package - "mikey179/vfsstream". Then I have run the phpunit tests and found working properly.

Please close the issue if you found no issues.

**Comment by Greg0** [comment]
Yup, now it passed without errors. Thanks
