### ISSUE TITLE
Why after last update , i executed insert() method on current class i cant get increment id

### ISSUE THREAD

**Issue by noistudio** [Greg0/Lazer-Database#62]
Why after last update , i executed insert() method on current class i cant get increment id and return null ,
because in Database.php in method save() on line 812  
if this line 
` $this->set = new \stdClass();`
commented // 
id is return correct.
Fix plz.

**Comment by anant-svc** [comment]
@noistudio I can confirm the issue and will fix it. I will push the fix as soon as possible.

**Comment by noistudio** [comment]
The question is next, why  confirm changes and not tested it? 
I use your package in my system  http://github.com/noistudio/art_laravel 
Plz fix this . It  important

**Comment by anant-svc** [comment]
@noistudio I have fixed that issue in new release version 1.2.0 #63
