### ISSUE TITLE
About limit()

### ISSUE THREAD

**Issue by shuyudao** [Greg0/Lazer-Database#64]
`/**
     * Pending function for limit()
     */
    protected function limitPending()
    {
        $offset     = $this->pending['limit']['offset'];
        $num        = $this->pending['limit']['number'];

        //Are these two parameters reversed?  $offset, $num
        // $this->data = array_slice($this->data,$offset, $num );

       //Change to the following，i can find out the data
       $this->data = array_slice($this->data, $num ,$offset);  
    }`

**Comment by anant-svc** [comment]
@shuyudao Please let me the issue you are facing.

**Comment by shuyudao** [comment]
> @shuyudao Please let me the issue you are facing.

`$data = $this->code->orderBy('id', 'DESC')->limit(0,10)->findAll()->asArray();`

The content I query through it is empty，But if I modify your source code, I can find it

**Comment by anant-svc** [comment]
Yes, @Greg0 is right, first parameter is limit and second is an offset or page number:
https://github.com/Greg0/Lazer-Database/blob/fbee5977618160d697daed677f0ae80f06bc4dd4/src/Classes/Database.php#L704

So you have change the position of the parameters like:

> $data = $this->code->orderBy('id', 'DESC')->limit(**10,0**)->findAll()->asArray();`

@shuyudao try the above code and let us know. If it is working then close the issue.

**Comment by shuyudao** [comment]
ok，thanks
